# Generated by Django 5.2.4 on 2025-07-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_id_alter_rating_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='average_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
