# Generated by Django 5.2.4 on 2025-07-05 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_rating_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='average_score',
        ),
        migrations.AlterField(
            model_name='rating',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='projects.project'),
        ),
    ]
